[package]
name = "fressian-wasm-demo"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde-fressian =  { git = "https://github.com/pkpkpk/serde-fressian", rev = "22e4ddc" }
serde = "1.0.70"
serde_derive = "1.0.70"
maplit = "1.0.1"

[profile.release]
opt-level = "s"
